version: "3"
services:
  redis:
    image: "redis:6.0.8-alpine"
    ports:
      - "6379:6379"
    volumes:
      - "./db/redis_data:/data"

  api:
    build: .
    volumes:
      - ./:/go/src/github.com/kons16/graphql-todo
    ports:
      - '8080:8080'
    depends_on:
      - redis
    command: sh -c "fresh;"
